apiVersion: v1
kind: Service
metadata:
  name: admin-panel
spec:
  type: NodePort
  selector:
    app: admin-panel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # Access via http://localhost:30001
