apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-panel
  template:
    metadata:
      labels:
        app: admin-panel
    spec:
      containers:
      - name: admin-panel
        # Since the admin-panel image is failing to pull, use a temporary nginx image for testing
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "300m"
            memory: "384Mi"
          requests:
            cpu: "150m"
            memory: "192Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
