apiVersion: v1
kind: Secret
metadata:
  name: notification-service-env
type: Opaque
stringData:
  PORT: "3000"
  MONGO_URI: 'mongodb+srv://pahan:pahan123@eatsy-services.1bfu4cv.mongodb.net/notificationdb?retryWrites=true&w=majority&appName=eatsy-services'
