apiVersion: v1
kind: Secret
metadata:
  name: order-service-env
type: Opaque
stringData:
  PORT: "3000"
  MONGO_URI: 'mongodb+srv://pahan:pahan123@eatsy-services.1bfu4cv.mongodb.net/orderdb?retryWrites=true&w=majority&appName=eatsy-services'
  JWT_SECRET: 'your_super_secret_key'
  USER_SERVICE_URL: 'http://localhost:30080/api'