apiVersion: v1
kind: Secret
metadata:
  name: restaurant-service-env
type: Opaque
stringData:
  PORT: "3000"
  MONGO_URI: 'mongodb+srv://dinithi:dinithi123@eatsy-services.1bfu4cv.mongodb.net/restaurantdb?retryWrites=true&w=majority&appName=eatsy-services'
  JWT_SECRET: "your_super_secret_key"
  USER_SERVICE_URL: "http://user-service:3000/api"
  ORDER_SERVICE_URL: "http://order-service:3000/api"
